# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_nonmemtools_wrappers", use_symbols = TRUE, package_name = "nonmemtools")

#' @docType package
#' @usage NULL
#' @useDynLib nonmemtools, .registration = TRUE
NULL

parse_ext_file_impl <- function(path) .Call(wrap__parse_ext_file_impl, path)


# nolint end
